### ISSUE TITLE
[FATAL] Major security flaw

### ISSUE THREAD

**Issue by PlanetTheCloud** [ZykeNetwork/Project-Burger#1]
The file 

- https://github.com/ZykeNetwork/Project-Burger/blob/master/process/login.php
- https://github.com/ZykeNetwork/Project-Burger/blob/master/process/register.php
- https://github.com/ZykeNetwork/Project-Burger/blob/master/process/edit_profile.php
- https://github.com/ZykeNetwork/Project-Burger/blob/master/process/forget_password.php
- https://github.com/ZykeNetwork/Project-Burger/blob/master/process/request_activate_account.php
Is just a few that I noticed that lack CSRF and Type Injection Prevention.

**Comment by PlanetTheCloud** [comment]
Any progress on this?

**Comment by ranakhas** [comment]
We are not going make this Project Complex and it is for beginners and students we tried to make it simple and easy to understand and work on it further. V1.0.0 will be final and complete release of Burger.

**Comment by PlanetTheCloud** [comment]
Hi, I understand this is for beginners BUT even if this is for beginners, security must present and shall have minimal flaw as possible.

The flaw I discovered can allow anyone to impersonate anyone.

**Comment by ghost** [comment]
#4

**Comment by PlanetTheCloud** [comment]
Hi @SirLothus , This issue is NOT the cause for the site (http://trimax.tk/) to be down.

**Comment by khasrana** [comment]
Hope so, will revise this in near future.
