### ISSUE TITLE
Lack of security and session check

### ISSUE THREAD

**Issue by yagiz-dev** [ZykeNetwork/Project-Burger#3]
lol, i didn't even login and i can access https://trimax.tk/edit_profile.php

I think you should check every page first before publishing :)

**Comment by yagiz-dev** [comment]
Same goes for change_password.php

**Comment by ranakhas** [comment]
Dear Sir, 
We have following pages as restricted for those who are login
    
    'profile.php',
    'change_password.php',
    'edit_profile.php',
    'logout.php',
Demo at trimax.tk is old and buggy, you can access lastest version at burger.zyke.us.to
